Lesson14 hw interface
YurySubbota/homeworks pull request #15
Opened 2023-12-10 19:20 UTC by YurySubbota

ДЗ
Создать программу которая работает с файлом. Выглядит она сл. образом:

def app():
    fw = FileWorker('path_to_file.txt')
    content = fw.read()
    print(content)
    fw.append('obj1')
    fw.append('obj2')
    fw.close()

app()

FileWorker должен уметь определять тип файла ( json | txt ) и в зависимости от типа, вызывать нужный
интерфейс (JsonHandler | TxtHandler)
Оба этих интерфейса наследуются от базового интерфейса BaseHandler который обязывает
реализовать 3 метода (read & append & close)
JsonHandler должен проверять что содержание файла - это список, что бы успешно реализовать метод
append.
read - должен возвращать либо список с объектами (если это json файл) либо строку (если txt)
close - закрывает файл.

2023-12-11 07:37 UTC, nicilytop-tms requested changes

2023-12-11 07:37 UTC, nicilytop-tms commented on lesson14_homework_interface/homework_14.py
> +        except FileNotFoundError:
I think better to raise this exception - because this is File HANDLER.. And this name looks like this class will only handle existing files

2023-12-11 07:37 UTC, nicilytop-tms commented on lesson14_homework_interface/homework_14.py
> +        except FileNotFoundError:
also here.. this is unnecessary .. You already check it on step when created instance of this class

2023-12-11 07:37 UTC, nicilytop-tms commented on lesson14_homework_interface/homework_14.py
> +        except FileNotFoundError:
and here..

2023-12-11 07:37 UTC, nicilytop-tms commented on lesson14_homework_interface/homework_14.py
> +        if self.path.lower().endswith('.json'):  # if end of string .json
use dict instead of `if` operator

2023-12-11 12:21 UTC, YurySubbota commented on lesson14_homework_interface/homework_14.py
> +        except FileNotFoundError:
there is no such check in the TxtHandler in the __init__

2023-12-12 06:49 UTC, nicilytop-tms requested changes
correct it

2023-12-12 06:49 UTC, nicilytop-tms commented on lesson14_homework_interface/homework_14.py
> +        except FileNotFoundError:
I mean that this is unnecessary

2023-12-12 06:49 UTC, nicilytop-tms commented on lesson14_homework_interface/homework_14.py
> +        except FileNotFoundError:
+ why you read method check existing file? move it to another place if you want..
You can do it into Base class or define method for it into Base class

2023-12-14 14:52 UTC, nicilytop-tms commented on lesson14_homework_interface/homework_14.py
> +        super().__init__(path)
you launch `init` of you Base class twice. here - is the first launching
When you try to create `JsonHandler` - there you launch `Base.__init__` the second time

2023-12-14 14:52 UTC, nicilytop-tms commented on lesson14_homework_interface/homework_14.py
> +        super().__init__(path)
Draw structure of classes. And you can see there when u creating `FileWorker` - you launching `create_file` of you`Basehandler`.. you dont override this method into you fileworker..
And also - better to launch `super.init` only from some Handler..

2023-12-19 09:58 UTC, merged